server:
  port: 9955
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: captureHead
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    database: 11
    lettuce:
      pool:
        max-active: 16
        max-wait: 3000ms
        max-idle: 16
        min-idle: 0
